defaultPhotoProfile = "https://media.istockphoto.com/id/1341046662/vector/picture-profile-icon-human-or-people-sign-and-symbol-for-template-design.jpg?s=612x612&w=0&k=20&c=A7z3OK0fElK3tFntKObma-3a7PyO8_2xxW0jtmjzT78="

photoUrls = [
    "https://fastly.picsum.photos/id/820/600/600.jpg?hmac=ejPZq7cnibOxtEWwBnDIetBdlXSSBuV165fGsycNy2E",
    "https://fastly.picsum.photos/id/858/600/600.jpg?hmac=7aIa-Hom7ifFVaT7PXOY63MfhBRuqQkUdv9Zsl9lsoM",
    "https://fastly.picsum.photos/id/779/600/600.jpg?hmac=cZSU0odp6R89tpcej__4l_RsEscmtZJhrSpQYccXRRo",
    "https://fastly.picsum.photos/id/379/600/600.jpg?hmac=i4-5KVJ_lHtfrru2SJYtf7nswyahn_U0Vg0f_i8CjXE",
    "https://fastly.picsum.photos/id/1001/600/600.jpg?hmac=RmKSHosLEMCqxbgpuRM5WTfwO8ma1-qEyDARbFr4_uQ",
    "https://fastly.picsum.photos/id/1053/600/600.jpg?hmac=-2qkx8KgDiiBvZ-qVpSoGFJ5cz8DxnSRCNe08YRO5bA",
    "https://fastly.picsum.photos/id/328/600/600.jpg?hmac=Mgtp8fRV2QsFB_tEF0Z_oUoQXmva7qsdzJi3f8JE0fg",
    "https://fastly.picsum.photos/id/186/600/600.jpg?hmac=2Cl1bSzjdwBxCHIP_wVJtGCBPu8CKSin5FPoqBolLhs",
    "https://fastly.picsum.photos/id/316/600/600.jpg?hmac=LKiBkeF2Isjk4db__md4HOfS1W1zdOKzWQtTnBTFKa4",
    "https://fastly.picsum.photos/id/44/600/600.jpg?hmac=H9S-5V2Dq-UlxWdnWPlrIAzFCeU1oEmQkl4KrYLIK58",
    "https://fastly.picsum.photos/id/249/600/600.jpg?hmac=CbEyzK5isfLq85yEpTHhVNKmO51bHfMdsjotutTc2yQ",
    "https://fastly.picsum.photos/id/660/600/600.jpg?hmac=4rVIUewVKJ3NB2E5_3RBZbykNxc6pRWUsWVjBulOup4",
    "https://fastly.picsum.photos/id/731/600/600.jpg?hmac=xwUino3EBDqsyVllX1f8rb8LTlkPnNfUVTozStpL_HI",
    "https://fastly.picsum.photos/id/861/600/600.jpg?hmac=btm2b-slXMjxggnz0tyAen8AJzSGDOdVht4vV87I7UY",
    "https://fastly.picsum.photos/id/848/600/600.jpg?hmac=pXLhg8_nYKyobESXqdUh9th-tG0hh5WUAluONXi1E6Y",
    "https://fastly.picsum.photos/id/572/600/600.jpg?hmac=78Q-TcBoedSQY4TkHP4kWBwcAZ6BIp15Ixd61bKJECY",
    "https://fastly.picsum.photos/id/191/600/600.jpg?hmac=vOqOdKxsq-PBtl9tAGYrxiz73ef_wInliRhZglWdKcg",
    "https://fastly.picsum.photos/id/912/600/600.jpg?hmac=O7ePZaS2tMxczRCfNQizxtZXCxd1nkWX5k96RrFbL98",
    "https://fastly.picsum.photos/id/293/600/600.jpg?hmac=D5OGPwFAA7ZIFf8jCPkncsbp99WIOaNucJqoMof1E-s",
    "https://fastly.picsum.photos/id/134/600/600.jpg?hmac=Zi7qKEBg1JdNbwVDfhMqOc23N5keWKAvwtkvjO_1D70",
    "https://fastly.picsum.photos/id/1004/600/600.jpg?hmac=okkphWAP4rOTU7TUbPyZaXElIKTmHiptABIAoscjQkU",
    "https://fastly.picsum.photos/id/31/600/600.jpg?hmac=WebFxt3Qyc4yiIlEcv7LcoUl5q2GrD2RlioeMcPY2kY",
    "https://fastly.picsum.photos/id/509/600/600.jpg?hmac=kbFfy3eA9yAzjUpVAWBX5zoyUFFwKbMPbZX7pgLPIsM",
    "https://fastly.picsum.photos/id/188/600/600.jpg?hmac=Itg2p6UT_1xDyBj3Bq0mU55qVLU1Mx2LnPVhkwxurAs",
    "https://fastly.picsum.photos/id/1080/600/600.jpg?hmac=xMzJ6qMqgNPEpWsyg7iqCcXTNXbehg6zrZhl5QxmivQ",
    "https://fastly.picsum.photos/id/409/600/600.jpg?hmac=xRckFdQw-9EqxUqK4CFcDvwkJJYQWKf4-NQ2M_hTvBI",
    "https://fastly.picsum.photos/id/565/600/600.jpg?hmac=R4GPV7Kh2f2K_Eci8y9bgqVhdPUD9T7bfUQnkGV9soQ",
    "https://fastly.picsum.photos/id/981/600/600.jpg?hmac=cLbEvWcCtsqC35CJ4Pv87iXtWXqKxyKNluti6frx3Rk",
    "https://fastly.picsum.photos/id/212/600/600.jpg?hmac=LQtNHENLISXSk8bxlT0mqX6KCaGt1lJtKn1w9rLatPY",
    "https://fastly.picsum.photos/id/609/600/600.jpg?hmac=Ul8A9kfDpLTbkRK6tbMbTrjRxIJKKs-J3EYc8olZ1fA",
    "https://fastly.picsum.photos/id/930/600/600.jpg?hmac=MpRC3PNWm70-R0dcaO-v4U-STsjEl2Z3rIIuw4AOD_w",
    "https://fastly.picsum.photos/id/480/600/600.jpg?hmac=OUFw8jvGVJfprI052Ge11X_2oXPmabwA3AEct7g60QY",
    "https://fastly.picsum.photos/id/9/600/600.jpg?hmac=euyc2e7Ry1SLZPY50Wo9PdaOydcryz28rxjj1099qa4",
    "https://fastly.picsum.photos/id/905/600/600.jpg?hmac=DvIKicBZ45DEZoZFwdZ62VbmaCwkK4Sv7rwYzUvwweU",
    "https://fastly.picsum.photos/id/63/600/600.jpg?hmac=4n9AYLnbScjTI99ndw_x93hjOB5_ggZ9tmPPw9TGIRU",
    "https://fastly.picsum.photos/id/643/600/600.jpg?hmac=w43TKLHeAAf6Asbkudid64Jy-BGi7SNkMI6GTTRC_CY",
    "https://fastly.picsum.photos/id/573/600/600.jpg?hmac=h4RSLJXtxR686jwtI_05tcXnp3UutZEaT-4kyxDsBF8",
    "https://fastly.picsum.photos/id/1012/600/600.jpg?hmac=UpJXwkVhderzI90UslalN4158PMvTQnq0LR5UlDKyoM",
    "https://fastly.picsum.photos/id/535/600/600.jpg?hmac=N-BmwAnkdn8AupmTxjXrwM_bW58Tj13GgBqtszBr7GI",
    "https://fastly.picsum.photos/id/552/600/600.jpg?hmac=4g2Xu5c4UtQbEHInHBFqZhGFYjoMQP-1EvooZ68EK5U",
    "https://fastly.picsum.photos/id/14/600/600.jpg?hmac=j6WWX3fWMXTJb1xYS2jDUcRPb8obR0PbEXycU1C_NEk",
    "https://fastly.picsum.photos/id/855/600/600.jpg?hmac=PB4Q6bLPxODl_Uxyzo843UiHzbwpP1lqCtqWE5xcJaM",
    "https://fastly.picsum.photos/id/879/600/600.jpg?hmac=8QrPLU3Zj8OaLCd6OL_CqgOaPzw6u6Lr-i_yyUMP4Uk",
    "https://fastly.picsum.photos/id/299/600/600.jpg?hmac=51mhCHMKu2mIIrRCoy8lFOfxBo9ETMCaIb_ho8C7XyA",
    "https://fastly.picsum.photos/id/1006/600/600.jpg?hmac=BKGVDYxDU4NAKE6eca7lrsiGWzkS2ejOhDGEO8S_iO8",
    "https://fastly.picsum.photos/id/267/600/600.jpg?hmac=fpMnJNVwhSx5rFluSWGIIVihUajYpC196e_JIp9GYKs",
    "https://fastly.picsum.photos/id/457/600/600.jpg?hmac=7MwgJYWcGFoxrvADiT7pAo9iRGp2BMy04-EqHsaQVNc",
    "https://fastly.picsum.photos/id/469/600/600.jpg?hmac=yDJk-E5wLG0Cy1BhcwWoRApxUOYD4IjtKPysjW0vvAQ",
    "https://fastly.picsum.photos/id/111/600/600.jpg?hmac=lcOMUfnTHx39V8ZXAD0efwM33vmYs4I70hQGDILdRqI",
    "https://fastly.picsum.photos/id/719/600/600.jpg?hmac=1q45aclFnkzu-iEnjJamWFQ4fN_5zwz1d1uguTvmr9U",
    "https://fastly.picsum.photos/id/151/600/600.jpg?hmac=w_FbzueE5Io6ShCJK5YSIGnGPe8mkRCMrvElTFLigw8",
    "https://fastly.picsum.photos/id/355/600/600.jpg?hmac=AZDDU8kuG3ZJHqaK2qmadQJuorh_MPX_vbwSSJNJs1E",
    "https://fastly.picsum.photos/id/275/600/600.jpg?hmac=3HEb8gkrgrQlOli0G65Q0Cai9wRtAQTjbPwuEXI2TvM",
    "https://fastly.picsum.photos/id/158/600/600.jpg?hmac=5wEdYHSg2lo2Met8Nf6579LX3wPuneDOs9cJTJ_CdMs",
    "https://fastly.picsum.photos/id/559/600/600.jpg?hmac=w4zg0TUhTkdONfFzRK39BC2ZnYhY97H7FMq9eIVAyNM",
    "https://fastly.picsum.photos/id/962/600/600.jpg?hmac=C7ghwO0M1Mp7dwqS86CWzlDN5bkTjyrqph-QTgnCxAU",
    "https://fastly.picsum.photos/id/1045/600/600.jpg?hmac=SArFO4VVNP7P_518PpQjzL-tNYPbObcpiRNV6p_Drho",
    "https://fastly.picsum.photos/id/959/600/600.jpg?hmac=8iYxVGEbg0wg2uiUuOFW0JUeo5BxV-eif0rRn4Rlr8M",
    "https://fastly.picsum.photos/id/31/600/600.jpg?hmac=WebFxt3Qyc4yiIlEcv7LcoUl5q2GrD2RlioeMcPY2kY",
    "https://fastly.picsum.photos/id/486/600/600.jpg?hmac=TSomFpU0dMQw2eJrmUF3P5pIJXs7F765cwNSNk_dULc",
    "https://fastly.picsum.photos/id/943/600/600.jpg?hmac=IbrSSHtdGtVHReCUYDgqgj9ngGrhtPVg9rHlEZeLH7k",
    "https://fastly.picsum.photos/id/960/600/600.jpg?hmac=IhIhEkzdbDAcmaXRur_FWmkw4bDz4faKhno4GJ65vYg",
    "https://fastly.picsum.photos/id/534/600/600.jpg?hmac=a68b3ddxCh9CF0DQ6U0xWkpwrecGujDZYFwaydxZDn8",
    "https://fastly.picsum.photos/id/1058/600/600.jpg?hmac=pOqYij0HzQFaxMUVmffDWO3nvizo3HmySCAuV1HMy_U",
    "https://fastly.picsum.photos/id/785/600/600.jpg?hmac=N2o4Rk736PXgpt7fGuSyOIMEyZPVv7qFh8YRr6TXw9Y",
    "https://fastly.picsum.photos/id/477/600/600.jpg?hmac=OZtbERNeoD6KqAZ8ZmwuKl0u5mJoGs4eM7hpZPw3VRU",
    "https://fastly.picsum.photos/id/15/600/600.jpg?hmac=a_HZyXevYAO7_IFaYdzkqlPUN__pN_lPBuV1Kt3afrY",
    "https://fastly.picsum.photos/id/350/600/600.jpg?hmac=qygOCTG8J1uzuKYOrLcdXG3rHsHDrg1bl11B3vkoS58",
    "https://fastly.picsum.photos/id/217/600/600.jpg?hmac=xxk0u3L_xgq4CGo8JNq60eYb3Vdv05QOZEdAs2kFVCk",
    "https://fastly.picsum.photos/id/237/600/600.jpg?hmac=KGSiyZ1y0xEcvk6vZQwzHW4bpTWEoXsMnRK6qbyBSAU",
    "https://fastly.picsum.photos/id/177/600/600.jpg?hmac=NLpNGTOav6MVzQYy8A-nulwg64bHHUVUWBy_LHsQDwQ",
    "https://fastly.picsum.photos/id/193/600/600.jpg?hmac=NxIjAPnPS4V7t4ArwOmg4blEualu1xddd6JCLNCHelI",
    "https://fastly.picsum.photos/id/27/600/600.jpg?hmac=czdZMe0esxZo8fnoCtkxJd2snl8C6QF5uQcNR8rHWho",
    "https://fastly.picsum.photos/id/484/600/600.jpg?hmac=9OHSJscWrVZfDlxHGHF6sxgB8sKwcvTmft5ItihZ0GU",
    "https://fastly.picsum.photos/id/777/600/600.jpg?hmac=FtIxsvZCNotAsB7mpFSLJpu0BjZfsLAArkSHQ7g-dHo",
    "https://fastly.picsum.photos/id/455/600/600.jpg?hmac=o3utFw5sYq4sCWe6TUb4JgI5quAo2i9DIex0Z9njmWo",
    "https://fastly.picsum.photos/id/460/600/600.jpg?hmac=dg-jlLsJs5Fnr9V8vDd1p-ybMGRF_yGqjkFf_Rw8esM",
    "https://fastly.picsum.photos/id/824/600/600.jpg?hmac=TGKdYU_Ke1F5dAGpvVon6YT5Sz99aiC6rRpFZ09aiRw",
    "https://fastly.picsum.photos/id/785/600/600.jpg?hmac=N2o4Rk736PXgpt7fGuSyOIMEyZPVv7qFh8YRr6TXw9Y",
    "https://fastly.picsum.photos/id/872/600/600.jpg?hmac=YhTzmU5yvfkReGhoDq1ysbo1MCZLcod7MfRxRNnoc0Q",
    "https://fastly.picsum.photos/id/909/600/600.jpg?hmac=OtpsdT-8ChIiNHvAf8HyEPN8xXir-43LIBzyn6euk0U",
    "https://fastly.picsum.photos/id/837/600/600.jpg?hmac=1NEsGpF2l8nfRG4Daz3oVeiGjVc2tC4ZdttYzH5-a70",
    "https://fastly.picsum.photos/id/906/600/600.jpg?hmac=-pZP67W1OKTygHivRaUZ2gYizUNK5IdPw5JnaPcStWI",
    "https://fastly.picsum.photos/id/429/600/600.jpg?hmac=5y02A4B5KCtL8KZzjVwFFsd4AWd5aRYoPBDnfERIKPc",
    "https://fastly.picsum.photos/id/146/600/600.jpg?hmac=3VaDzOGy_6-Yz8cupDVkhKMyfh4aCVA3Qk-H7t1W2x0",
    "https://fastly.picsum.photos/id/837/600/600.jpg?hmac=1NEsGpF2l8nfRG4Daz3oVeiGjVc2tC4ZdttYzH5-a70",
    "https://fastly.picsum.photos/id/6/600/600.jpg?hmac=f4u_WK_hTE9w5oTKFccWDjA8HkgaCfbt4sqpEXRRMRs",
    "https://fastly.picsum.photos/id/583/600/600.jpg?hmac=yXtgbHkfW6svyWVnKzWVSbcOAKVAlgV0kp4oW3gExaw",
    "https://fastly.picsum.photos/id/449/600/600.jpg?hmac=PQ7w_GECRTwxZNh3wE841cH8p4kC6WTCQ4el-tcc3Xs",
    "https://fastly.picsum.photos/id/149/600/600.jpg?hmac=IUZ-DWK8zg0bbDfTRiES5SEwboog32Ynn4s5TPE6Dzs",
    "https://fastly.picsum.photos/id/468/600/600.jpg?hmac=L3MGp24xOOJQ6KMolcB9d3TsI90PFs58BG62DFEYjFo",
    "https://fastly.picsum.photos/id/344/600/600.jpg?hmac=-dcLtsgcwMMURdpKxFbyHU6q9zYSiTZ99e_HWBKzdkc",
    "https://fastly.picsum.photos/id/939/600/600.jpg?hmac=3Wqe_tg1c6mHKO4FaCshJEWj2RqdLuzwX3u5a27v_aA",
    "https://fastly.picsum.photos/id/265/600/600.jpg?hmac=HV0FZIgV4wx4hjDEhylNguScSYkVB-PhfyN34uYS0d0",
    "https://fastly.picsum.photos/id/643/600/600.jpg?hmac=w43TKLHeAAf6Asbkudid64Jy-BGi7SNkMI6GTTRC_CY",
    "https://fastly.picsum.photos/id/444/600/600.jpg?hmac=l2WCfoWvjDAjGWTUizn-mKrSbKG56CUi3xQV_XqfQ9Q",
    "https://fastly.picsum.photos/id/294/600/600.jpg?hmac=7uCsi46bWIKEKnIqkyoVJGjseueKPXDqJ9uUkM5rWFw",
    "https://fastly.picsum.photos/id/36/600/600.jpg?hmac=WNp8GMbFjhaBKF6RhEqfuG3XTGdlDnsTWC_qFLr0TTw",
    "https://fastly.picsum.photos/id/984/600/600.jpg?hmac=pqb18_v31kddPUzBRAYyTFLVE-6VXrNJsL98mA33z4o",
    "https://fastly.picsum.photos/id/686/600/600.jpg?hmac=tDHiEbVm8bxOFZLHfTK0LM0wsNtOk4rYiZc_up8zoIk",
]

allBusinessInterests = [
    "Marketplace",
    "E-commerce",
    "Retail",
    "Wholesale Trade",
    "Import/Export",
    "Franchise Opportunities",
    "Home Services",
    "Vehicle Maintenance",
    "Appliance Repair",
    "Electronics Repair",
    "Construction Materials",
    "Art and Crafts",
    "Woodworking",
    "Metalworking",
    "Ceramics",
    "Jewelry Making",
    "Graphic Design",
    "Photography",
    "Digital Art",
    "Illustration",
    "Fashion Design",
    "Interior Design",
    "Web Design",
    "Education and Training",
    "Language Learning",
    "Online Courses",
    "EdTech",
    "Cultural Education",
    "Skill Development Programs",
    "Craft Beer Brewing",
    "Wine Production",
    "Coffee Roasting",
    "Restaurant Franchising",
    "Catering Services",
    "Food Truck Business",
    "Tech Hardware",
    "Renewable Energy",
    "Drone Technology",
    "Green Energy Solutions",
    "Biomedical Engineering",
    "Civil Engineering",
    "Financial Services",
    "Fintech",
    "Insurance",
    "Personal Finance Management",
    "Investment Banking",
    "Wealth Management",
    "Credit Services",
    "Healthcare",
    "Fitness and Gym",
    "Mental Health Services",
    "Personalized Nutrition Services",
    "Telemedicine",
    "Home Healthcare Services",
    "Cosmetics",
    "Pharmaceuticals",
    "Software Development",
    "AI-powered Assistants",
    "AR/VR Entertainment",
    "Robotics Automation",
    "3D Printing Services",
    "Digital Identity Solutions",
    "Web3 Projects",
    "Metaverse Development",
    "Cloud Computing Services",
    "Data Analytics",
    "Cybersecurity Solutions",
    "Legal Services",
    "Online Legal Services",
    "Legal Consulting",
    "Intellectual Property Law",
    "Contract Law",
    "Immigration Law",
    "Transportation and Logistics",
    "Supply Chain Management",
    "Freight Forwarding",
    "Warehousing",
    "Inventory Management",
    "Courier and Delivery Services",
    "Business Consulting",
    "Project Management Services",
    "Operations Management",
    "Change Management Consulting",
    "Strategic Planning Services",
    "Human Resources Consulting",
    "Politics",
    "Government Relations Firm",
    "Public Policy Consulting",
    "Lobbying Services",
    "Political Campaign Management",
    "Election Consulting",
    "Real Estate Renting",
    "Real Estate Trading",
    "Property Management",
    "Property Development",
    "Bed and Breakfast",
    "Biotechnology",
    "Bioengineering",
    "MedTech",
    "Research and Development",
    "Scientific Consulting",
    "Security and Defense",
    "Surveillance Equipment Manufacturer",
    "Security Training Academy",
    "Risk Assessment Services",
    "Security Consulting",
    "Event Planning",
    "Gaming",
    "Music Production",
    "Film Production",
    "Theme Parks",
    "Live Performances",
    "Streaming Services",
    "Talent Management",
    "Celebrity Booking",
    "Party Equipment Rental",
    "Travel Agencies",
    "Tour Operators",
    "Hotel Management",
    "Vacation Rentals",
    "Guided Tours",
    "Adventure Tourism",
    "Eco-Tourism",
    "Cultural Experiences",
    "Cruise Lines",
    "Travel Insurance",
    "Crop Farming",
    "Livestock Farming",
    "Organic Farming",
    "Hydroponics",
    "Agricultural Equipment Manufacturing",
    "Farm Management Software",
    "Agri-Tourism",
    "Farmers Markets",
    "Seed Production",
    "Agricultural Consulting",
    "Renewable Energy Installation",
    "Solar Panel Manufacturing",
    "Wind Turbine Manufacturing",
    "Energy Consulting",
    "Energy Efficiency Solutions",
    "Power Plant Construction",
    "Battery Technology",
    "Electric Vehicle Charging Infrastructure",
    "Energy Storage Solutions",
    "Smart Grid Technology",
    "Digital Marketing",
    "Journalism",
    "Public Relations",
    "Social Media Management",
    "Content Creation",
    "Advertising",
    "Broadcasting",
    "Therapy Services",
    "Mindfulness Practices",
    "Emotional Support",
    "Mental Health Education",
    "Nutritional Counseling",
    "Dietary Planning",
    "Nutrition Education",
    "Specialized Diets",
    "Municipal Services",
    "Urban Development",
    "Public Infrastructure",
    "Waste Management",
    "Environmental Sustainability",
    "Business Process Automation",
    "Digital Integration",
    "Industrial Automation",
    "Advanced Technologies Adoption",
    "Housekeeping Services",
    "Industrial Cleaning",
    "Sanitation Products",
    "Personal Hygiene Products",
    "Green Solutions",
    "Conservation Programs",
    "Eco-friendly Products",
    "Home Care for Seniors",
    "Assisted Living Facilities",
    "Senior Support Services",
    "Elderly Products and Equipment",
    "Sports Organizations",
    "Recreational Activities",
    "Outdoor Adventure",
    "Fitness Clubs",
    "Non-profit Organizations",
    "Social Work",
    "Community Support Programs",
    "Volunteer Services",
    "Scientific Research",
    "Innovation Projects",
    "Technology Incubation",
    "R&D Partnerships",
]

allSkills = [
    "Agronomy",
    "Farming",
    "Horticulture",
    "Hydroponics",
    "Sustainable Agriculture",
    "Brand Management",
    "Digital Marketing",
    "Linguistic Competences",
    "Public Relations",
    "Public Speaking",
    "Social Media Management",
    "Business Development",
    "Customer Relationship Management",
    "Market Analysis",
    "Market Research",
    "Sales Strategy",
    "Carpentry",
    "Electrical Wiring",
    "Masonry",
    "Plumbing",
    "Roofing",
    "Auto Maintenance and Repair",
    "Appliance Maintenance and Repair",
    "Painting",
    "Flooring Installation",
    "HVAC Installation and Repair",
    "Concrete Work",
    "Drywall Installation and Repair",
    "Mechanical Work",
    "Electronics Repair",
    "Jewelry Making",
    "Metalworking",
    "Pottery",
    "Sculpture",
    "Woodworking",
    "Glassblowing",
    "Leatherworking",
    "Ceramics",
    "Blacksmithing",
    "Weaving",
    "Acting",
    "Fashion Design",
    "Film Production",
    "Graphic Design",
    "Illustration",
    "Music Composition",
    "Music Production",
    "Photography",
    "Writing",
    "Adult Education",
    "Curriculum Development",
    "Educational Technology",
    "Teaching/Instruction",
    "Training and Development",
    "Baking",
    "Cooking",
    "Food Pairing",
    "Gourmet Cooking",
    "Wine Tasting",
    "Aerospace Engineering",
    "Building Architecture",
    "Chemical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Environmental Impact Reduction",
    "Mechanical Engineering",
    "Natural Resource Management",
    "Renewable Energy",
    "Sustainable Development",
    "Accounting",
    "Financial Analysis",
    "Financial Planning",
    "Investment Management",
    "Taxation",
    "Childcare",
    "Elderly Care",
    "Medicine",
    "Nursing",
    "Personal Training",
    "Pharmacy",
    "Physical Therapy",
    "Psychology",
    "Surgery",
    "Backend Development",
    "Blockchain",
    "Cybersecurity",
    "Data Analysis",
    "Database Management",
    "Frontend Development",
    "IoT",
    "Machine Learning and AI",
    "Mobile Development",
    "Network Management",
    "Software Architecture",
    "UI/UX Design",
    "Virtual Reality",
    "Web Development",
    "Contract Law",
    "Corporate Law",
    "Criminal Law",
    "Data Privacy and Compliance",
    "Intellectual Property Law",
    "Legal Research",
    "Distribution Strategy",
    "Inventory Management",
    "Logistics Coordination",
    "Supply Chain Management",
    "Warehouse Management",
    "HR Management",
    "Leadership Development",
    "Project Management",
    "Strategic Planning",
    "Team Building",
    "Time Management",
    "Diplomacy and International Relations",
    "Government and Public Administration",
    "Political Analysis",
    "Biology",
    "Chemistry",
    "Environmental Science",
    "Mathematics",
    "Neuroscience",
    "Physics",
    "Statistics",
    "Civil Protection",
    "Crisis Management",
    "Emergency Management",
    "Surveillance and Control Technologies",
    "Tactical Training",
    "Work Security",
    "Catering",
    "Customer Support",
    "Event Planning",
    "Janitorial Work",
    "Pest Control",
]

allHobbies = [
    "Photography",
    "Cooking",
    "Hiking",
    "Painting",
    "Playing a Musical Instrument",
    "Gardening",
    "Reading",
    "Writing",
    "Drawing",
    "Camping",
    "Fishing",
    "Traveling",
    "Bird Watching",
    "Knitting",
    "Embroidery",
    "Pottery",
    "Sculpting",
    "Woodworking",
    "Metalworking",
    "DIY Projects",
    "Collecting Stamps",
    "Collecting Coins",
    "Collecting Antiques",
    "Collecting Vinyl Records",
    "Collecting Comic Books",
    "Collecting Action Figures",
    "Collecting Sports Memorabilia",
    "Collecting Postcards",
    "Collecting Rocks and Minerals",
    "Model Building",
    "Calligraphy",
    "Dancing",
    "Yoga",
    "Meditation",
    "Running",
    "Swimming",
    "Cycling",
    "Skateboarding",
    "Surfing",
    "Skiing",
    "Snowboarding",
    "Rock Climbing",
    "Bungee Jumping",
    "Skydiving",
    "Scuba Diving",
    "Sailing",
    "Kayaking",
    "Canoeing",
    "Rafting",
    "Horseback Riding",
    "Archery",
    "Shooting",
    "Golfing",
    "Tennis",
    "Badminton",
    "Table Tennis",
    "Soccer",
    "Basketball",
    "Baseball",
    "Softball",
    "Volleyball",
    "Bowling",
    "Billiards",
    "Chess",
    "Backgammon",
    "Card Games",
    "Board Games",
    "Video Games",
    "Watching Movies",
    "Watching TV Series",
    "Listening to Music",
    "Attending Concerts",
    "Going to the Theater",
    "Visiting Museums",
    "Cooking Classes",
    "Wine Tasting",
    "Beer Brewing",
    "Attending Food Festivals",
    "Volunteering",
    "Community Service",
    "Socializing",
    "Picnicking",
    "Barbecuing",
    "Attending Sporting Events",
    "Attending Music Festivals",
    "Attending Comic Conventions",
    "Attending Gaming Conventions",
    "Attending Anime Conventions",
    "Karaoke",
    "Cultural Festivals",
    "Celebrating Holidays",
    "Urban Exploration",
    "Ghost Hunting",
    "Stargazing",
    "Geocaching",
    "Astrology",
    "Tarot Card Reading",
    "Paintball",
    "Airsoft",
    "LARPing",
    "Cosplay",
    "Bodybuilding",
    "Weightlifting",
    "Powerlifting",
    "CrossFit",
    "Parkour",
    "Freerunning",
    "Tricking",
    "Bouldering",
]


def get_random_photo(iterations_num, width=600, height=600, category="profile"):
    import requests
    for i in range(0, iterations_num):
        percent = (100 * i) / iterations_num
        if percent % 5 == 0:
            print(f"Creazione url foto al {percent} %...")
        url = f"https://picsum.photos/{width}/{height}?random&category={category}"

        response = requests.get(url)

        if response.status_code == 200:
            photo_url = response.url
            photoUrls.append(photo_url)
        else:
            print(
                f"Errore: Impossibile recuperare la foto. Codice di stato: {response.status_code}"
            )


# get_random_photo(100)
# print(photoUrls)